# Endpoint to pull annoucements
asx_announcements_url: https://www.asx.com.au/asx/1/company/%s/announcements?count=20&market_sensitive=true

# List of Tickers
tickers: ['1AE','1MC','AEE','NRZ','REZ']

# headers
headers: {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
